#!/bin/sh
set -eu

: "${VISIONFLOW_APP_PASSWORD:?VISIONFLOW_APP_PASSWORD is required}"
: "${VISIONFLOW_MIGRATOR_PASSWORD:?VISIONFLOW_MIGRATOR_PASSWORD is required}"

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=app_password="$VISIONFLOW_APP_PASSWORD" \
  --set=migrator_password="$VISIONFLOW_MIGRATOR_PASSWORD" <<'SQL'
CREATE ROLE visionflow_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'app_password';
CREATE ROLE visionflow_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD :'migrator_password';

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE visionflow TO visionflow_app, visionflow_migrator;
GRANT USAGE ON SCHEMA public TO visionflow_app;
GRANT USAGE, CREATE ON SCHEMA public TO visionflow_migrator;

ALTER DEFAULT PRIVILEGES FOR ROLE visionflow_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO visionflow_app;
ALTER DEFAULT PRIVILEGES FOR ROLE visionflow_migrator IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO visionflow_app;
SQL
